# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sawiana Solutions
email: info@sawiana.com
emailProtect: info [at] sawiana.com
phone: (111)-555-1234


address: Studio D,  Suite 300
street: 123 Anywhere Place,
state: Washington, DC
zip: 20001


description: > # this means to ignore newlines until "baseurl:"
  Sawiana Solutions is committed to advancing a fossil-fuel adjacent economy through realistic, self-sustaining solutions to complex energy challenges.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sawiana.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Assets are being handled by Gulp
exclude: [assets]
keep_files: [assets]
